name: 'Goblet Deploy'
description: 'Deploy your Goblet App'
author: 'Austen Novis'
inputs:
  project:
    description: gcloud project to deploy to
    required: true
  location:
    description: region to deploy to
    required: true
  goblet-path:
    description: Path to a goblet app directory in which `main.py`, `requirements.txt` and `.goblet\` should be stored
    required: false
    default: ''
  stage:
    description: deployment stage
    required: false
    default: ''
  envars:
    description: |-
      list of key, value pairs that should be added to the function's environment variables
      written as '{k1}:{v1},{k2}:{v2},...'
    required: false
    default: ''
branding:
  icon: upload-cloud
  color: blue
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.location }}
    - ${{ inputs.goblet-path }}
    - ${{ inputs.stage }}
    - ${{ inputs.envars }}
