name: 'Goblet Deploy'
description: 'Deploy your Goblet App'
author: 'Austen Novis'
inputs:
  config:
    description: |-
      json string of any config overrides
    required: false
branding:
  icon: upload-cloud
  color: blue
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config }}
